INSERT INTO CAR_TYPE (PRICE, TYPE) VALUES (250, 'Hatchback')
INSERT INTO CAR_TYPE (PRICE, TYPE) VALUES (300, 'Sedan')
INSERT INTO CAR_TYPE (PRICE, TYPE) VALUES (350, 'SUV')

INSERT INTO CAR (BRAND, MODEL, ID_CAR_TYPE, IS_ACTIVE) VALUES ('Toyota', 'Yaris', 1, 1)
INSERT INTO CAR (BRAND, MODEL, ID_CAR_TYPE, IS_ACTIVE) VALUES ('Ford', 'Taurus', 2, 1)
INSERT INTO CAR (BRAND, MODEL, ID_CAR_TYPE, IS_ACTIVE) VALUES ('Hyundai', 'HRV', 3, 1)